apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
spec:
  containers:
  - name: httpd-container
    image: httpd
    ports:
    - containerPort: 80
      hostPort: 80
  nodeSelector:
    kubernetes.io/hostname: minikube
